
---

- hosts: web

  gather_facts: yes

  become: true

  tasks:
  - name: MongoDB - Import public key
    apt_key:
      keyserver: hkp://keyserver.ubuntu.com:80
      id: EA312927

  - name: MongoDB - Add repository
    apt_repository:
      filename: '/etc/apt/sources.list.d/mongodb-org-3.2.list'
      repo: 'deb https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse'
      state: present
      update_cache: yes

  - name: Update sources list
    command: tee /etc/apt/sources.list.d/mongodb-org-3.2.list
    become: true

  - name: MongoDB - Install MongoDB
    apt:
      name: mongodb-org
      state: present
      update_cache: yes

  - name: MongoDB - Running state
    service:
      name: mongod
      state: started